version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend/devops-task-manager
    depends_on:
      - backend
    ports:
      - "8080:80"
